// ============================================================
// Familien-App – Beispiel-Daten (Default-Daten)
// ------------------------------------------------------------
// Diese Datei wird in index.html VOR dem Hauptscript geladen
// (<script src="default-data.js">) und stellt zwei Funktionen
// bereit:
//   window.buildDefaultData(CONFIG)   → Beispiel-Daten (Packliste,
//                                       Einkauf, Todos, Reinigung)
//   window.buildFamilyRecipes(CONFIG) → Rezept-Pools für den
//                                       KI-Menüplaner
// Alle Personennamen werden dynamisch aus CONFIG abgeleitet –
// für eine neue Familie muss hier normalerweise NICHTS angepasst
// werden. CONFIG.useDefaultData = false → Daten werden ignoriert.
// ============================================================
'use strict';

window.buildDefaultData = function(CONFIG) {
    const memberNames = CONFIG.members.map(m => m.name);
    const kidNames = CONFIG.kids.map(k => k.name);
    const allNames = memberNames.concat(kidNames);
    const parent1 = memberNames[0] || 'Elternteil 1';
    const parent2 = memberNames[1] || parent1;
    const parentsLabel = memberNames.join(' & ') || 'Eltern';

    // Fortlaufende IDs für Packlisten-Items
    let nextId = 0;
    const item = (text, tag, note) => ({ id: ++nextId, text: text, checked: false, tag: tag || '', note: note || '' });

    // ---------- Packliste: 1 neutraler Beispiel-Trip ----------
    const categories = {};

    // Eine Kleider-Kategorie pro Kind (Tag = Kindername).
    // Babys (description enthält "Baby") bekommen eine Baby-Packliste.
    CONFIG.kids.forEach(kid => {
        const isBaby = (kid.description || '').toLowerCase().includes('baby');
        categories['👗 Kleider ' + kid.name] = isBaby ? [
            item('Bodies (5–6)', kid.name),
            item('Strampler / Hosen (3–4)', kid.name),
            item('Shirts / Oberteile (3–4)', kid.name),
            item('Pyjamas (2–3)', kid.name),
            item('Schlafsack', kid.name),
            item('Jäckchen / Pullover (2)', kid.name),
            item('Söckli (4 Paar)', kid.name),
            item('Mützli (Sonne + warm)', kid.name),
            item('Nuscheli / Halstücher', kid.name),
            item('Ersatzkleider (Spuck-Reserve)', kid.name)
        ] : [
            item('Hosen (2–3)', kid.name),
            item('Shirts / Bodies (3–4)', kid.name),
            item('Pyjama (2)', kid.name),
            item('Pullover / Jäckchen', kid.name),
            item('Socken (3 Paar)', kid.name),
            item('Schuhe + Hausschuhe', kid.name),
            item('Mützen (Sonne + warm)', kid.name),
            item('Regenjacke & Regenhose', kid.name)
        ];
    });

    categories['👔 ' + parentsLabel] = [
        item('Outfits gemäss Wetter (2–3)'),
        item('Pyjamas'),
        item('Unterwäsche & Socken'),
        item('Jacken'),
        item('Kulturbeutel (Zahnbürste, Cremes)'),
        item('Shampoo / Duschgel'),
        item('Badesachen'),
        item('Sonnencreme LSF 50+'),
        item('Sonnenbrillen')
    ];

    categories['🧷 Pflege & Hygiene Kinder'] = [
        item('Windeln (falls noch gebraucht)'),
        item('Feuchttücher (1–2 Packungen)'),
        item('Wickelunterlage (faltbar)'),
        item('Popocreme'),
        item('Zahnbürste & Zahnpasta Kinder'),
        item('Nuggis / Ersatznuggis'),
        item('Kinder-Sonnencreme LSF 50+')
    ];

    categories['🍼 Essen & Trinken Kinder'] = [
        item('Snacks (Reiswaffeln, Fruchtriegel)'),
        item('Trinkflaschen Kinder'),
        item('Teller / Besteck Kinder'),
        item('Lätzchen')
    ];

    categories['💊 Reiseapotheke'] = [
        item('Fieberthermometer'),
        item('Nasenspray Kinder'),
        item('Hustensirup Kinder'),
        item('Pflaster & Verbandmaterial'),
        item('Zäpfli (Fieber, Schmerzen)', '', 'Dosierung passend zum Alter'),
        item('Ibuprofen Erwachsene'),
        item('Wundsalbe / Bepanthen'),
        item('Desinfektionsmittel'),
        item('Pinzette & Zeckenzange'),
        item('Insektenschutz'),
        item('Medikamente (eigene)')
    ];

    categories['🚗 Transport & Unterwegs'] = [
        item('Kindersitze ins Auto'),
        item('Kinderwagen / Buggy mit Regencover'),
        item('Trage / Tragetuch (falls gebraucht)')
    ];

    categories['🎨 Spielen & Beschäftigung'] = [
        item('Lieblings-Kuscheltiere', '', 'Nicht vergessen!'),
        item('Vorlesebücher / Gutenachtgeschichten'),
        item('Malzeug / Stifte & Malbuch'),
        item('Spielzeug (kleine Auswahl)'),
        item('Kopfhörer (Kinder + Erwachsene)')
    ];

    categories['⚡ Technik'] = [
        item('Ladekabel für alles'),
        item('Powerbank')
    ];

    categories['📄 Dokumente & Finanzen'] = [
        item('Ausweise und Krankenkassenkarten', '', 'Kinder brauchen eigenen Pass/ID'),
        item('Europäische Krankenversicherungskarte'),
        item('Bargeld / Karten'),
        item('Notfallnummern-Liste', '', 'Kinderarzt, Pannendienst'),
        item('Impfausweis Kinder')
    ];

    categories['✅ Vor Abreise'] = [
        item('Kühlschrank checken / leeren'),
        item('Pflanzen giessen / organisieren'),
        item('Haustiere versorgen / organisieren'),
        item('Müll rausbringen')
    ];

    return {
        menu: {},
        packliste: {
            activeTrip: 'ausflug',
            trips: {
                ausflug: {
                    trip: {
                        name: 'Wochenend-Ausflug',
                        destination: '',
                        duration: '2–3 Tage',
                        people: allNames
                    },
                    categories: categories
                }
            }
        },
        shopping: [
            { id: 1, text: 'Rüebli', category: 'Gemüse', checked: false },
            { id: 2, text: 'Spinat', category: 'Gemüse', checked: false },
            { id: 3, text: 'Tomaten', category: 'Gemüse', checked: false },
            { id: 4, text: 'Zwiebeln', category: 'Gemüse', checked: false },
            { id: 5, text: 'Äpfel', category: 'Früchte', checked: false },
            { id: 6, text: 'Poulet', category: 'Fleisch & Fisch', checked: false },
            { id: 7, text: 'Eier', category: 'Milchprodukte', checked: false },
            { id: 8, text: 'Milch', category: 'Milchprodukte', checked: false },
            { id: 9, text: 'Brot', category: 'Brot & Gebäck', checked: false }
        ],
        todos: [
            { id: 1, text: 'Altpapier rausbringen', checked: false, priority: 'high', assignee: 'beide' },
            { id: 2, text: 'Zahnarzttermin vereinbaren', checked: false, priority: 'medium', assignee: parent1 },
            { id: 3, text: 'Wäsche aufhängen', checked: false, priority: 'low', assignee: 'beide' },
            { id: 4, text: 'Elternabend Schule', checked: false, priority: 'high', assignee: 'beide' },
            { id: 5, text: 'Velo-Pneu aufpumpen', checked: false, priority: 'low', assignee: parent2 }
        ],
        reinigung: [
            { id: 1, text: 'Staubsaugen (alle Räume)', checked: false, frequency: 'weekly', lastDone: '', note: '' },
            { id: 2, text: 'Böden wischen', checked: false, frequency: 'weekly', lastDone: '', note: '' },
            { id: 3, text: 'Badezimmer reinigen', checked: false, frequency: 'weekly', lastDone: '', note: '' },
            { id: 4, text: 'Küche gründlich reinigen', checked: false, frequency: 'weekly', lastDone: '', note: '' },
            { id: 5, text: 'Staubwischen', checked: false, frequency: 'biweekly', lastDone: '', note: '' },
            { id: 6, text: 'Betten frisch beziehen', checked: false, frequency: 'biweekly', lastDone: '', note: '' },
            { id: 7, text: 'Ecken und Ränder der Böden reinigen', checked: false, frequency: 'monthly', lastDone: '', note: 'Dort wo der Staubsauger nicht hinkommt' },
            { id: 8, text: 'Spinnweben entfernen', checked: false, frequency: 'monthly', lastDone: '', note: 'Ecken, Decken, Keller' },
            { id: 9, text: 'Kühlschrank auswischen', checked: false, frequency: 'monthly', lastDone: '', note: '' },
            { id: 10, text: 'Backofen reinigen', checked: false, frequency: 'quarterly', lastDone: '', note: '' },
            { id: 11, text: 'Abflüsse reinigen', checked: false, frequency: 'quarterly', lastDone: '', note: 'Bad, Küche, Dusche' },
            { id: 12, text: 'Fenster putzen (innen)', checked: false, frequency: 'quarterly', lastDone: '', note: '' },
            { id: 13, text: 'Waschmaschine reinigen (Hygienespüler)', checked: false, frequency: 'quarterly', lastDone: '', note: '' },
            { id: 14, text: 'Wintergarten reinigen', checked: false, frequency: 'biannual', lastDone: '', note: 'Boden, Glasflächen, Möbel' },
            { id: 15, text: 'Fenster putzen (aussen)', checked: false, frequency: 'biannual', lastDone: '', note: '' },
            { id: 16, text: 'Matratzen absaugen & lüften', checked: false, frequency: 'biannual', lastDone: '', note: '' },
            { id: 17, text: 'Vorhänge / Gardinen waschen', checked: false, frequency: 'biannual', lastDone: '', note: '' },
            { id: 18, text: 'Tiefkühler abtauen', checked: false, frequency: 'biannual', lastDone: '', note: '' },
            { id: 19, text: 'Dachrinnen kontrollieren / reinigen', checked: false, frequency: 'annual', lastDone: '', note: '' },
            { id: 20, text: 'Teppiche / Polstermöbel tiefenreinigen', checked: false, frequency: 'annual', lastDone: '', note: '' },
            { id: 21, text: 'Keller aufräumen & reinigen', checked: false, frequency: 'annual', lastDone: '', note: '' },
            { id: 22, text: 'Garage / Abstellraum aufräumen', checked: false, frequency: 'annual', lastDone: '', note: '' },
            { id: 23, text: 'Heizkörper reinigen', checked: false, frequency: 'annual', lastDone: '', note: '' },
            { id: 24, text: 'Markisen / Storen reinigen', checked: false, frequency: 'annual', lastDone: '', note: '' },
            { id: 25, text: 'Dunstabzugshaube / Filter reinigen', checked: false, frequency: 'quarterly', lastDone: '', note: '' },
            { id: 26, text: 'Geschirrspüler reinigen', checked: false, frequency: 'quarterly', lastDone: '', note: '' }
        ]
    };
};

// ============================================================
// Rezept-Pools für den KI-Menüplaner
// (allgemein, 4 Saisons, Schweizer Klassiker, Low-Carb-Znacht)
// ============================================================
window.buildFamilyRecipes = function(CONFIG) {
    return {
        allgemein: [
            'Grüner Spargel mit Sauce Hollandaise und St. Galler Kartoffeln',
            'Tomaten-Mozzarella-Salat mit frischem Brot',
            'Bündner Gerstensuppe',
            'Baked Feta Pasta',
            'Pho Bo',
            'Pizza (selbstgemacht)',
            'Wurst vom Grill mit Salat',
            'Risotto',
            'Ungarisches Gulasch',
            'Spaghetti Bolognese',
            'Wienerli im Teig mit Salat',
            'Ricotta-Gnocchi',
            'Szegediner Gulasch',
            'Flammkuchen',
            'Croque Monsieur',
            'Tiroler Speckknödel',
            'Gefüllte Omelette mit Champignons & Hackfleisch',
            'Blumenkohl-Steak mit Bohnenpüree & Chimichurri',
            'Pouletgeschnetzeltes mit Salat',
            'Fondue',
            'Selbstgemachte Pasta',
            'Lasagne',
            'Asiatische Nudeln mit Rindfleisch & Gemüse',
            'Ofengemüse mit Fleisch',
            'Borschtsch',
            'Ofengemüse mit Fisch',
            'Raclette',
            'Hacktätschli mit Reis und Champignonsauce',
            'Fleischkäse mit Salat',
            'Ricotta aus dem Backofen mit Salat',
            'Lasagne mit Kürbis & Ziegenkäse',
            'Kartoffel-Lauch-Suppe',
            'Gebackener Camembert mit Salat',
            'Geschnetzeltes Stroganoff mit Hörnli',
            'Hackbraten mit Kartoffelstock und Erbsen',
            'Selbstgemachte Cheeseburger mit Ofenkartoffeln',
            'Pulled-Chicken-Tacos mit Mais',
            'Gnocchi mit Tomaten und Mozzarella',
            'Spätzli mit Rahmschnitzel',
            'Penne all\'Arrabbiata',
            'Tortilla-Wraps mit Poulet und Gemüse',
            'Reispfanne mit Poulet und Gemüse',
            'Kartoffelpuffer mit Apfelmus',
            'Quiche Lorraine mit Salat',
            'Hackfleisch-Kartoffel-Auflauf',
            'Spaghetti Aglio e Olio',
            'Bratreis mit Ei und Gemüse',
            'Hähnchenschenkel aus dem Ofen mit Kartoffel-Wedges',
            'Fischstäbli mit Kartoffelstock und Erbsen',
            'Käse-Lauch-Suppe mit Hackfleisch',
            'Linsensuppe mit Wienerli',
            'Tomatensuppe mit Grilled-Cheese-Sandwich',
            'Gefüllte Paprika mit Hackfleisch und Reis',
            'Kohlrabi-Schnitzel mit Kräuterquark',
            'Rührei mit Speck und Röstkartoffeln',
            'Hörnli und Ghackets mit Apfelmus',
            'Pasta mit Thunfisch-Tomatensauce',
            'Pizzabrötchen mit Salat',
            'Gemüse-Lasagne',
            'Riz Casimir mit Poulet',
            'Geschnetzeltes mit Champignons und Nudeln',
            'Ofenkartoffeln mit Quark und Salat',
            'Kartoffelgnocchi mit Salbeibutter',
            'Maispoulet mit Reis und Gemüse',
            'Spinat-Ricotta-Tortelloni mit Tomatensauce',
            'Selbstgemachte Hähnchen-Nuggets mit Pommes',
            'Bratwurst mit Rösti und Apfelmus',
            'Eglifilet mit Mandelbutter und Kartoffeln',
            'Pasta al Pesto Rosso mit Cherrytomaten',
            'Couscous mit Ofengemüse und Feta',
            'Mildes Hähnchencurry mit Reis',
            'Kartoffelsalat mit Cervelat',
            'Gefüllte Crêpes mit Schinken und Käse',
            'Currywurst mit Ofenkartoffeln und Salat',
            'Pasta mit Zitronen-Rahmsauce und Broccoli',
            'Hot Dogs mit Krautsalat',
            'Käsewähe mit grünem Salat',
            'Poulet-Piccata mit Tomatenspaghetti',
            'Tortellini-Gratin mit Schinken',
            'Poulet-Fajitas mit Paprika und Mais',
            'Chicken Teriyaki mit Basmatireis',
            'Poke Bowl mit Lachs und Reis',
            'Gemüse-Curry mit Basmatireis',
            'Kichererbsen-Eintopf mit Brot',
            'Nasi Goreng mit Spiegelei',
            'Mie-Nudeln mit Poulet und Cashewnüssen',
            'Bifteki mit Reis und Tzatziki',
            'Moussaka mit grünem Salat',
            'Paella mit Poulet und Crevetten',
            'Spanische Tortilla mit Salat',
            'Pita-Taschen mit Falafel und Joghurtsauce',
            'Hähnchen-Döner im Fladenbrot',
            'Pulled-Beef-Burger mit Süsskartoffel-Pommes',
            'Bauernomelette mit Kartoffeln und Speck',
            'Zucchetti-Piccata mit Tomatenreis',
            'Lachs-Teriyaki mit Sesamreis',
            'Fischknusperli mit Tartarsauce und Salzkartoffeln',
            'Penne mit Ricotta-Spinat-Sauce',
            'Gnocchi-Pfanne mit Cherrytomaten und Rucola',
            'Kartoffel-Hackfleisch-Pfanne mit Paprika',
            'Pilaw-Reis mit Poulet und Erbsen',
            'Polenta-Schnitten mit Tomatensauce und Salat',
            'Wraps mit Hackfleisch und Bohnen',
            'Ofen-Frittata mit Kartoffeln und Lauch',
            'Spaghetti mit Zitronen-Garnelen',
            'Poulet-Saté-Spiesse mit Erdnusssauce und Reis',
            'Maccaroni-Auflauf mit Gemüse und Käse',
            'Udon-Nudeln mit Gemüse und Ei'
        ],
        fruehling: [
            'Bärlauchrisotto mit Parmesan',
            'Pasta mit grünen Erbsen, Minze und Ricotta',
            'Ofen-Lachs mit grünem Spargel',
            'Spinat-Quiche mit Frühlingszwiebeln',
            'Bärlauchpasta mit gerösteten Pinienkernen',
            'Lauwarmer Linsensalat mit gebratenem Spargel',
            'Spargelrisotto mit Zitronen-Crème-fraîche',
            'Rhabarber-Apero-Wähe pikant mit Salat',
            'Spinat-Cannelloni mit Ricotta',
            'Frühlings-Frittata mit jungem Spinat',
            'Spargel-Carbonara',
            'Bärlauch-Knödel mit brauner Butter',
            'Grüner-Spargel-Quiche mit Schinken',
            'Spargel-Kartoffel-Salat mit Ei',
            'Radieschen-Frischkäse-Brot mit Suppe',
            'Frühlingsgemüse-Pfanne mit Poulet',
            'Morchel-Rahmsauce mit Spätzli',
            'Spinat-Lachs-Lasagne',
            'Bärlauch-Frittata mit neuen Kartoffeln',
            'Spargel-Schinken-Gratin',
            'Erbsen-Pasta mit Pancetta',
            'Kalbsbratwurst mit grünem Spargel',
            'Frühlingszwiebel-Käsewähe',
            'Spargelsalat mit Ei und Schinken',
            'Spinat-Gnocchi mit Gorgonzola',
            'Grüne-Spargel-Pasta mit Zitrone',
            'Bärlauchsuppe mit Croûtons',
            'Frühlingsrollen-Bowl mit Glasnudeln',
            'Maispoulet mit jungen Karotten und Kartoffeln',
            'Spinatknödel mit Parmesan',
            'Spargel-Flammkuchen mit Ziegenfrischkäse',
            'Pouletbrust mit Rhabarber-Chutney und Reis',
            'Frühlingssuppe mit Gemüse und Flädli',
            'Gebratener grüner Spargel mit Burrata und Brot',
            'Erbsen-Minz-Suppe mit Brot',
            'Radieschen-Quark mit Pellkartoffeln',
            'Rüebli-Orangen-Suppe mit Brot',
            'Weisser Spargel mit Schinken und neuen Kartoffeln',
            'Zitronen-Poulet mit Frühlingsgemüse',
            'Süsskartoffel-Spinat-Curry mit Reis',
            'Bärlauch-Gnocchi mit Cherrytomaten',
            'Kohlrabi-Gratin mit Kartoffeln',
            'Lammvoressen mit Frühlingsgemüse und Kartoffelstock',
            'Mangold-Wähe mit Salat',
            'Frühlingsrisotto mit grünem Gemüse'
        ],
        sommer: [
            'Melonen-Feta-Salat mit Minze und Limettendressing',
            'Linsensalat mit Rucola, roten Zwiebeln und Zitrusdressing',
            'Frittata mit Sommerkräutern',
            'Couscous-Salat mit Kichererbsen, Gurke und Zitrone',
            'Shakshuka mit frischem Brot',
            'Thai-Nudel-Bowl mit Erdnuss-Dressing',
            'Lachs-Wraps mit Frischkäse und Rucola',
            'Asia-Nudeln mit Sesam und Gemüse',
            'Gegrillte Pouletspiesse mit Couscous-Salat',
            'Caprese-Spiesse mit Ciabatta',
            'Gazpacho mit Brot',
            'Grillierte Maiskolben mit Kräuterbutter',
            'Sommerliche Gemüse-Tarte',
            'Panzanella (toskanischer Brotsalat)',
            'Pasta-Salat mit Pesto und Cherrytomaten',
            'Lachs vom Grill mit Zucchini',
            'Halloumi-Burger mit Salat',
            'Kalte Caprese-Pasta',
            'Grillierte Cervelat mit Brot und Senf',
            'Gefüllte Zucchini mit Hackfleisch und Reis',
            'Wassermelonen-Feta-Spiesse mit Brot',
            'Gemischter Bruschetta-Teller',
            'Sommer-Frittata mit Zucchini',
            'Pouletflügeli vom Grill mit Maissalat',
            'Bunter Reissalat mit Mais und Schinken',
            'Grillgemüse mit Quinoa und Feta',
            'Hörnlisalat mit Schinken und Mais',
            'Vitello Tonnato mit Brot',
            'Zucchetti-Carpaccio mit Burrata und Brot',
            'Griechischer Bauernsalat mit Pita',
            'Tomaten-Tarte aus Blätterteig mit Salat',
            'Gefüllte Peperoni vom Grill mit Reis',
            'Sommerrollen mit Erdnusssauce',
            'Tabouleh mit gegrilltem Halloumi',
            'Tomatenrisotto mit Basilikum',
            'Kalte Gurkensuppe mit Joghurt und Brot',
            'Steak vom Grill mit Kräuterbutter und Country Cuts',
            'Pouletburger mit Mango und Salat',
            'Fischspiesse vom Grill mit Reissalat',
            'Ratatouille mit Polenta',
            'Nizza-Salat (Salade Niçoise)',
            'Spaghetti mit rohem Tomatensugo und Burrata',
            'Mais-Puffer mit Avocado-Dip',
            'Crevetten-Spiesse vom Grill mit Knoblauchbrot',
            'Gefüllte Auberginen mit Couscous'
        ],
        herbst: [
            'Kürbissuppe mit Kürbiskernöl',
            'Kürbisrisotto mit Salbei',
            'Pilzrisotto mit Steinpilzen',
            'Pasta mit Steinpilzen und Petersilie',
            'Rote-Bete-Risotto mit Ziegenkäse',
            'Geröstete Kürbisspalten mit Halloumi und Granatapfel',
            'Linseneintopf mit Wurst',
            'Ofen-Süsskartoffeln mit Hummus und Granatapfel',
            'Kürbis-Käse-Tarte mit Salat',
            'Ofenpoulet mit Wurzelgemüse',
            'Wildschweinragout mit Spätzli',
            'Hirschpfeffer mit Rotkraut und Knöpfli',
            'Kürbis-Gnocchi mit Salbeibutter',
            'Maroni-Risotto',
            'Federkohl-Eintopf mit Kartoffeln',
            'Apfel-Speck-Wähe mit Salat',
            'Kürbis-Lasagne',
            'Pilzragout auf Toast',
            'Ofen-Kürbis mit Feta und Granatapfel',
            'Süsskartoffel-Suppe mit Ingwer',
            'Geschmorte Hähnchenschenkel mit Wurzelgemüse',
            'Kürbis-Käse-Spätzli',
            'Federkohl-Pasta mit Knoblauch',
            'Steinpilz-Tagliatelle',
            'Birnen-Käse-Wähe mit Salat',
            'Kürbis-Hackfleisch-Auflauf',
            'Wirz-Kartoffel-Stampf mit Bratwurst',
            'Pastinaken-Karotten-Ofengemüse mit Poulet',
            'Kürbis-Kokos-Suppe mit Croûtons',
            'Maronisuppe mit Speck',
            'Gerösteter Blumenkohl mit Tahini und Bulgur',
            'Kürbis-Kichererbsen-Eintopf',
            'Selleriecremesuppe mit Apfelwürfeln',
            'Rosenkohl-Gratin mit Schinken',
            'Randen-Salat mit gebratenem Ziegenkäse und Brot',
            'Süsskartoffel-Gnocchi mit Salbeibutter',
            'Apfel-Curry mit Poulet und Reis',
            'Gulaschsuppe mit Brot',
            'Rehpfeffer mit Spätzli und Rotkraut',
            'Flädlisuppe mit Speckbrot',
            'Kabissuppe mit Hackbällchen',
            'Ofengeschmorter Fenchel mit Kartoffeln und Parmesan',
            'Birnen-Gorgonzola-Risotto',
            'Pilz-Knödel mit Rahmsauce',
            'Geschmorter Rindsbraten mit Karotten und Kartoffelstock'
        ],
        winter: [
            'Älplermagronen mit Apfelmus',
            'Käseschnitten mit Spiegelei und Salat',
            'Wirsing-Hackfleisch-Pfanne',
            'Schweinsbraten mit Rotkraut und Knödel',
            'Rotkraut-Dattel-Salat mit Feta und Granatapfel',
            'Linsen-Dal mit Naan-Brot',
            'Pastinaken-Cremesuppe mit Brot',
            'Bratwurst mit Zwiebelsauce und Rösti',
            'Kartoffelgratin mit Wintergemüse',
            'Kürbis-Curry mit Kichererbsen',
            'Hörnli-Auflauf mit Schinken und Käse',
            'Wirsing-Rouladen mit Hackfleisch',
            'Rindsvoressen mit Kartoffelstock',
            'Kohl-Hackfleisch-Auflauf',
            'Sauerkraut mit Kasseler und Kartoffelstock',
            'Linsen-Eintopf mit Speck',
            'Ofen-Rösti mit Speck und Ei',
            'Kartoffel-Käse-Auflauf',
            'Randen-Risotto mit Ziegenkäse',
            'Erbsensuppe mit Wienerli',
            'Wildgulasch mit Teigwaren',
            'Chicorée-Schinken-Gratin',
            'Käsefondue Moitié-Moitié',
            'Geschmortes Rindsragout mit Polenta',
            'Rosenkohl-Speck-Pfanne mit Kartoffeln',
            'Kartoffel-Wirz-Suppe mit Brot',
            'Hackbraten mit Rotkraut und Kartoffelstock',
            'Schweinsbraten mit Spätzli und Bohnen',
            'Gefüllte Wirsingwickel mit Kartoffelstock',
            'Raclette-Ofenkartoffeln mit Salat',
            'Gerstotto mit Wintergemüse',
            'Wintergemüse-Curry mit Reis',
            'Hühnersuppe mit Reis-Einlage',
            'Siedfleisch mit Bouillongemüse und Salzkartoffeln',
            'Chili con Carne mit Reis und Sauerrahm',
            'Lauch-Kartoffel-Gratin mit Schinken',
            'Schupfnudeln mit Sauerkraut und Speck',
            'Gratinierte Polenta mit Tomatensauce',
            'Ossobuco mit Risotto Milanese',
            'Gebratener Fisch mit Fenchel-Orangen-Salat',
            'Wirz-Eintopf mit Kartoffeln und Wienerli',
            'Zwiebelsuppe mit Käse-Croûtons',
            'Couscous mit Wintergemüse und Merguez',
            'Zitronen-Risotto mit gebratenem Poulet',
            'Bohnen-Eintopf mit Speck und Brot'
        ],
        // Kuratierte Klassiker aus swissmilk.ch / fooby.ch / migusto.migros.ch –
        // Standard-Schweizer-Familienküche, ergänzt deine 4 Listen, keine Doppelungen.
        klassiker_ch: [
            'Zürcher Geschnetzeltes mit Rösti',
            'Cordon Bleu mit Pommes Frites und Salat',
            'Capuns mit Speck und Sbrinz',
            'Maluns mit Apfelmus und Bergkäse',
            'Pizokel mit Speck und Käse',
            'Polenta mit Brasato (Bündner Schmorbraten)',
            'Bramata mit Pilzragout',
            'Saltimbocca alla Romana mit Polenta',
            'Gnocchi alla Sorrentina',
            'Pasta Carbonara',
            'Pasta alla Norma mit Auberginen',
            'Tortellini in Brodo',
            'Falafel-Bowl mit Hummus und Tabouleh',
            'Pouletcurry mit Basmatireis und Naan',
            'Lachs mit Honig-Senf-Glasur und Ofengemüse',
            'Forelle Müllerin Art mit Petersilienkartoffeln',
            'Chili sin Carne mit Maisbrot',
            'Burrito-Bowl mit schwarzen Bohnen und Avocado',
            'Pulled-Pork-Sandwich mit Coleslaw',
            'Gemüse-Pad-Thai mit Erdnüssen',
            'Tofu-Curry mit Kokosmilch und Jasminreis',
            'Bibimbap mit eingelegtem Gemüse',
            'Quinoa-Bowl mit gerösteter Süsskartoffel und Avocado',
            'Pilz-Stroganoff mit Spätzli',
            'Süsskartoffel-Curry mit Kokosmilch',
            'Tessiner Minestrone mit Pesto',
            'Marokkanische Couscous-Suppe mit Kichererbsen',
            'Schweinsmedaillons im Speckmantel mit Kartoffelgratin',
            'Ghackets mit Hörnli',
            'Pastetli mit Kalbsragout',
            'Chässpätzli mit Röstzwiebeln',
            'Rösti mit Bündnerfleisch und Spiegelei',
            'Schnitzel Wiener Art mit Kartoffelsalat',
            'Geschnetzeltes Berner Art mit Rösti',
            'Kalbsbraten mit Marktgemüse',
            'Pilzrahmschnitzel mit Nudeln',
            'Penne mit Gorgonzolasauce',
            'Spaghetti Napoli',
            'Polenta mit Spinat und Spiegelei',
            'Tagliatelle al Ragù',
            'Gefüllte Cannelloni mit Spinat und Ricotta',
            'Egli-Knusperli mit Kartoffelsalat',
            'Fish and Chips mit Erbsenpüree',
            'Pouletbrust mit Ratatouille und Reis',
            'Kalbsgeschnetzeltes mit Eierschwämmli',
            'Hähnchenschenkel im Backofen mit Gemüsereis',
            'Spinat-Ricotta-Wähe',
            'Zwiebelkuchen mit Salat',
            'Pasta Primavera',
            'Linguine alle Vongole',
            'Risi e Bisi',
            'Gemüse-Reis-Pfanne mit Cashew',
            'Tom Kha Gai mit Reis',
            'Butter Chicken mit Naan',
            'Köfte mit Bulgur und Joghurt',
            'Gyros mit Tzatziki und Reis',
            'Enchiladas mit Bohnen und Käse',
            'Quesadillas mit Poulet und Gemüse',
            'Ramen-Suppe mit Ei und Poulet',
            'Riz Casimir',
            'Älplermakkaroni Classic mit Apfelmus',
            'Gnocchi alla Sorrentina überbacken',
            'Pouletbrust mit Honig-Senf und Ofengemüse',
            'Hacktätschli mit Kartoffelstock und Rahmsauce',
            'Spaghetti mit Meeresfrüchten',
            'Wähe vom Blech mit Lauch und Speck',
            'Schweinschnitzel paniert mit Kartoffelpüree',
            'Gemüse-Dampfnudeln mit Curry'
        ],
        // Pool C – Low-Carb / No-Carb Znacht (Abendessen ohne Sättigungsbeilage
        // aus Pasta, Reis, Kartoffeln, Brot). Familientauglich, ≤45 Min.
        low_carb: [
            'Gebratene Pouletbrust mit Brokkoli und Kräuterbutter',
            'Lachsfilet mit Blattspinat und Zitrone',
            'Zucchini-Nudeln mit Bolognese',
            'Blumenkohlreis mit Pouletcurry',
            'Gefüllte Zucchini mit Hackfleisch und Käse überbacken',
            'Omelette mit Schinken, Käse und Salat',
            'Frittata mit Zucchini und Tomaten',
            'Caprese-Teller mit Avocado',
            'Gemischter Salat mit gebratenen Pouletstreifen',
            'Griechischer Salat mit Feta und Oliven',
            'Lachs-Spinat-Auflauf ohne Kartoffeln',
            'Blumenkohl-Käse-Gratin',
            'Hähnchenschenkel mit Ofengemüse (Zucchini, Paprika, Aubergine)',
            'Rindssteak mit grünen Bohnen und Kräuterbutter',
            'Eier-Avocado-Salat',
            'Gefüllte Champignons mit Frischkäse und Speck',
            'Zucchini-Lasagne (Zucchinischeiben statt Teigplatten)',
            'Auberginen-Auflauf mit Hackfleisch und Mozzarella',
            'Thai-Hähnchen-Pfanne mit Brokkoli',
            'Garnelen-Pfanne mit Knoblauch und Zucchini',
            'Blumenkohl-Steak mit Spiegelei',
            'Krautsalat mit gebratenem Speck',
            'Pouletspiesse mit Gurken-Joghurt-Dip',
            'Eglifilet mit Mandelbutter und Blattspinat',
            'Hüttenkäse mit Tomaten, Gurke und Schinken',
            'Brokkoli-Frittata mit Käse',
            'Gefüllte Paprika mit Hackfleisch und Feta (ohne Reis)',
            'Pouletgeschnetzeltes mit Champignonrahm und Blumenkohlreis',
            'Lachs-Tatar mit Avocado und Gurke',
            'Spinat-Feta-Omelette',
            'Hackbällchen in Tomatensauce mit Zucchininudeln',
            'Caesar Salad mit Pouletstreifen (ohne Croûtons)',
            'Rührei mit Räucherlachs und Avocado',
            'Gebratener Halloumi mit Tomatensalat',
            'Gemüsepfanne mit Pouletwürfeln und Sesam',
            'Zucchini-Puffer mit Kräuterquark',
            'Kohlrabi-Schinken-Gratin mit Käse',
            'Lammkoteletts mit grünen Bohnen',
            'Tofu-Gemüse-Pfanne mit Erdnusssauce',
            'Blumenkohl-Tabouleh mit Minze',
            'Avocado gefüllt mit Thunfisch',
            'Pilz-Omelette mit Schnittlauch',
            'Ofen-Lachs mit Fenchel und Zitrone',
            'Hähnchen-Frikadellen mit Gurkensalat',
            'Brokkoli-Hackfleisch-Pfanne mit Käse',
            'Gefüllte Tomaten mit Thunfisch und Mozzarella',
            'Geschmorte Pouletschenkel mit Rosenkohl',
            'Spargel-Schinken-Röllchen mit Sauce Hollandaise',
            'Gemüse-Curry mit Kokosmilch (ohne Reis)',
            'Zucchini-Boote mit Thunfisch überbacken',
            'Bunter Blattsalat mit Ei, Speck und Avocado',
            'Pouletbrust Caprese mit Mozzarella und Tomate',
            'Krautstiel-Gratin mit Käse',
            'Gebratene Felchen mit Zucchinigemüse',
            'Spiegeleier auf Spinat mit Parmesan',
            'Hähnchen-Gemüse-Spiesse vom Grill',
            'Sauerkraut mit Kasseler (ohne Kartoffeln)',
            'Blumenkohl-Suppe mit Speck',
            'Zucchini-Cremesuppe mit Crème fraîche',
            'Brokkoli-Cremesuppe mit gerösteten Mandeln',
            'Tomatensuppe mit Mozzarella-Einlage',
            'Antipasti-Teller mit Mozzarella und Schinken',
            'Gefüllte Aubergine mit Schafskäse',
            'Lachs-Spinat-Roulade',
            'Rinderhack-Auflauf mit Aubergine und Käse',
            'Gurken-Lachs-Röllchen mit Frischkäse',
            'Gegrillte Crevetten mit Avocado-Salsa',
            'Eierstich-Suppe mit Gemüse',
            'Pouletbrust mit Ofen-Federkohl und Parmesan',
            'Gebratenes Zanderfilet mit Mangold'
        ]
    };
};
